### ISSUE TITLE
3.2 branch: Move man pages to /usr/share/man

### ISSUE THREAD

**Issue by onodera-punpun** [6c37/crux-ports-git#1]

**Comment by kori** [comment]
Oh boy.
Alright, let's start work on this soon, and merge the 3.2 branch when 3.2 comes out.

**Comment by rtlanceroad** [comment]
So what I am thinking now is we need to keep 2 branches when 3.2 is released. One branch is for 3.1 users who don't want to put man-pages to /usr/share, the other one is for 3.2 users who want to mess /usr/share up.

**Comment by kori** [comment]
We don't support legacy.
Are you one of the users who don't want to move their manpages?

**Comment by rtlanceroad** [comment]
I..am not sure about it. But I like them to be seperated, at least kind of.

**Comment by kori** [comment]
I think the only reason I'm going to let this branch pass is because 3.2 is not out yet and merging it already would create a divergence in the filesystem layout.
But once it's out, I see no reason to support 3.1.

**Comment by rtlanceroad** [comment]
Ok. Let's follow the upstream.

**Comment by onodera-punpun** [comment]
Since the 3.2rc1 iso I'm gonna start updating some ports. So far I've done most of the ports I created, help appreciated :).

**Comment by arcetera2** [comment]
Also done (I think).
