### ISSUE TITLE
[notify] Patched screenfetch 

### ISSUE THREAD

**Issue by rtlanceroad** [6c37/crux-ports-git#12]
The patch is related to the screenfetch PR:  https://github.com/KittyKatt/screenFetch/pull/282 . If someone feels bad, feel free to commit.

**Comment by Wildefyr** [comment]
Just use ufetch :D

**Comment by rtlanceroad** [comment]
ufetch is an ideeded great alternative. But wrt to screenfetch itself, we need to fix it.

**Comment by rtlanceroad** [comment]
It seems everyone is ok with this, I'll close this.

**Comment by Wildefyr** [comment]
Well it's really on upstream's shoulders. If they don't wanna merge for whatever reason that's on them
