### ISSUE TITLE
question

### ISSUE THREAD

**Issue by neeasade** [6c37/crux-ports-git#14]
ok, so I'm a new crux user

why aren't these port names postfixed with like '-git' or something to indicate they are dev level/latest source? if I have 2 ports for bspwm, and one is git version and one is 0.9, how can I differentiate between them (I realize the first one listed in prt-get conf gets installed but it would be nice to not have to worry about order there). Is this done intentionally so that port names conflict with others? is there not a way to specify conflicting ports in crux?

Awesome repo(s), btw.
Thanks for reading.

**Comment by ix** [comment]
pkgutils doesn't support package conflicts

as this isn't an issue, I'm closing this

**Comment by neeasade** [comment]
I see, so that's why -- well if I may continue this further:

what if I wanted /some/ git ports from this repo, but there were other ports in this same repo that I wanted stable versions of, and I prioritize this ports collection over another that has the stable port. is there a way to bypass this ports collection in favor of falling through to the stable port, for select packages?

**Comment by ix** [comment]
I actually did this for mk from 6c37 (added CRUX package management utils) and mk from z3bra (plan 9 make); I renamed "mk" in the Pkgfile to "mk-crux". you could probably do the same, just manually copy and edit the Pkgfile.

**Comment by neeasade** [comment]
seems you just have to be really aware of what you're doing. 

Alright, thanks.
