### ISSUE TITLE
pianobar dependencies

### ISSUE THREAD

**Issue by maraku** [6c37/crux-ports-git#15]
ffmpeg is needed by pianobar but is currently not listed in the dependencies. also, c99 isn't provided by default in crux, but symlinking gcc to c99 seems to "fix" this.

**Comment by rtlanceroad** [comment]
Thank you for pointing it out @maraku :)  @onodera-punpun Can you update md5sum and footprint? :)

**Comment by maraku** [comment]
as to the second part (c99 problems), using
`sed -i 's|CC:=c99|CC:=gcc -std=c99|' Makefile`
before `make PREFIX=/usr` should work. This avoids symlink nastiness.

**Comment by onodera-punpun** [comment]
Just fixed this, thanks!
