### ISSUE TITLE
Failed make termite

### ISSUE THREAD

**Issue by lounqe** [6c37/crux-ports-git#17]
Error installing termite 

> =======> Building '/home/pkgmk/pkg/termite#git-1.pkg.tar.xz'.
cp fix-transparency.patch /home/pkgmk/work/termite/src
+ build
+ cd /home/pkgmk/src
+ cd termite
+ git fetch -q
+ git reset --hard origin/master
HEAD is now at a9cecb4 Merge pull request #400 from jelly/assert_valid_color
+ patch -Np1
patching file termite.cc
Hunk #1 succeeded at 1487 (offset 115 lines).
+ make
g++ -std=c++11 -O3 -Wall -Wextra -pedantic -Winit-self -Wshadow -Wformat=2 -Wmissing-declarations -Wstrict-overflow=5 -Wcast-align -Wconversion -Wunused-macros -Wwrite-strings -DNDEBUG -D_POSIX_C_SOURCE=200809L -DTERMITE_VERSION=\"v12\" -pthread -I/usr/include/vte-2.91 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -O2 -march=x86-64 -Wno-missing-field-initializers -s -Wl,--as-needed  termite.cc -lvte-2.91 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -o termite
termite.cc: In function 'void load_theme(GtkWindow*, VteTerminal*, GKeyFile*, hint_info&)':
termite.cc:1316:62: error: 'vte_terminal_set_color_cursor_foreground' was not declared in this scope
         vte_terminal_set_color_cursor_foreground(vte, &*color);
                                                              ^
termite.cc: In function 'int main(int, char**)':
termite.cc:1651:14: warning: 'gboolean gtk_window_parse_geometry(GtkWindow*, const gchar*)' is deprecated [-Wdeprecated-declarations]
         if (!gtk_window_parse_geometry(GTK_WINDOW(window), geometry)) {
              ^
In file included from /usr/include/gtk-3.0/gtk/gtkdialog.h:32:0,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from termite.cc:32:
/usr/include/gtk-3.0/gtk/gtkwindow.h:443:10: note: declared here
 gboolean gtk_window_parse_geometry   (GtkWindow   *window,
          ^
termite.cc:1651:14: warning: 'gboolean gtk_window_parse_geometry(GtkWindow*, const gchar*)' is deprecated [-Wdeprecated-declarations]
         if (!gtk_window_parse_geometry(GTK_WINDOW(window), geometry)) {
              ^
In file included from /usr/include/gtk-3.0/gtk/gtkdialog.h:32:0,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from termite.cc:32:
/usr/include/gtk-3.0/gtk/gtkwindow.h:443:10: note: declared here
 gboolean gtk_window_parse_geometry   (GtkWindow   *window,
          ^
termite.cc:1651:68: warning: 'gboolean gtk_window_parse_geometry(GtkWindow*, const gchar*)' is deprecated [-Wdeprecated-declarations]
         if (!gtk_window_parse_geometry(GTK_WINDOW(window), geometry)) {
                                                                    ^
In file included from /usr/include/gtk-3.0/gtk/gtkdialog.h:32:0,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from termite.cc:32:
/usr/include/gtk-3.0/gtk/gtkwindow.h:443:10: note: declared here
 gboolean gtk_window_parse_geometry   (GtkWindow   *window,
          ^
make: *** [Makefile:36: termite] Error 1
=======> ERROR: Building '/home/pkgmk/pkg/termite#git-1.pkg.tar.xz' failed.

-- Packages where install failed
termite

>

**Comment by rtlanceroad** [comment]
@lounqe I made a [PR](https://github.com/thestinger/termite/pull/402) for this error. If you want to bypass error now, add the following before `patch -Np1 < $SRC/fix-transparency.patch` 
```
sed -i 's|vte_terminal_set_color_cursor_foreground(vte, &*color)|vte_terminal_set_color_foreground(vte, &*color)|' termite.cc
```
That should work.
