### ISSUE TITLE
wmutils-opt doesn't install

### ISSUE THREAD

**Issue by volumetricsteve** [6c37/crux-ports-git#19]
Using the 6c37-git.httpup method to get items with prt-get, I get a Footprint Mismatch error on wmutils-opt.   Crux 3.2 X86_64

**Comment by rtlanceroad** [comment]
@volumetricsteve sync repo and try again, it should work now.

**Comment by volumetricsteve** [comment]
Thank you, seems good to go now.

**Comment by rtlanceroad** [comment]
Nice
