### ISSUE TITLE
Dunst error building

### ISSUE THREAD

**Issue by lounqe** [6c37/crux-ports-git#20]
Check out dunst I got error building it.

+ cd dunst
+ make
fatal: No names found, cannot describe anything.
Option release requires an argument
make: *** [Makefile:48: docs/dunst.1] Error 1
make: *** Waiting for unfinished jobs....
=======> ERROR: Building '/home/pkgmk/pkg/dunst#git-2.pkg.tar.xz' failed.
prt-get: error while install

**Comment by rtlanceroad** [comment]
You failed here:
In `Makefile`:
```
pod2man --name=dunst -c "Dunst Reference" --section=1 --release=${VERSION} $< > $@
```
The `VERSION` variable is defined in `config.mk`:
```
VERSION := $(shell git describe --tags)
```

So `git describe --tags` wont work, so `--release` takes nothing. 

I am on a vocation without cpmputer around, but you can do something about that `VERSION` variable(check git man page to let it work preper)or wait for @onodera-punpun to give a fix. 
:)

**Comment by onodera-punpun** [comment]
This should be fixed now.
