### ISSUE TITLE
Termite signature

### ISSUE THREAD

**Issue by gigavinyl** [6c37/crux-ports-git#21]
The termite port throws a `Signature mismatch` error.

**Comment by rtlanceroad** [comment]
Hi, which driver are you using, httpup or git?  If you are using httpup, you may have encountered signature mismatch, because we don't have updated httpup for a while. In this case, I recommend you to pass `-is` to `pkgmk` or `prt-get` to bypass signature check. I'll fix when i am not busy.

**Comment by rtlanceroad** [comment]
I've pushed several commits to the repo, try sync it again and problem should get fixed.
