### ISSUE TITLE
Mpv package fail to building

### ISSUE THREAD

**Issue by mariojuniorjp** [6c37/crux-ports-git#22]
Hi. I trying to compile mpv git, but this error appears:

Waf: Leaving directory `/usr/ports/work/mpv/src/mpv/source/mpv/build'
'build' finished successfully (9.545s)
[mpv-build] Success: built: libass ffmpeg mpv
+ cd source/mpv
+ ./waf install --destdir=/usr/ports/work/mpv/pkg
Waf: Entering directory `/usr/ports/work/mpv/src/mpv/source/mpv/build'
[1/1] Compiling version.sh
+ install /usr/ports/work/mpv/pkg/usr/local/share/doc/mpv/mplayer-input.conf (from etc/mplayer-input.conf)
+ install /usr/ports/work/mpv/pkg/usr/local/share/doc/mpv/input.conf (from etc/input.conf)
+ install /usr/ports/work/mpv/pkg/usr/local/share/doc/mpv/restore-old-bindings.conf (from etc/restore-old-bindings.conf)
+ install /usr/ports/work/mpv/pkg/usr/local/share/doc/mpv/mpv.conf (from etc/mpv.conf)
+ install /usr/ports/work/mpv/pkg/usr/local/share/man/man1/mpv.1 (from build/DOCS/man/mpv.1)
+ install /usr/ports/work/mpv/pkg/usr/local/share/applications/mpv.desktop (from etc/mpv.desktop)
+ install /usr/ports/work/mpv/pkg/usr/local/etc/mpv/encoding-profiles.conf (from etc/encoding-profiles.conf)
+ install /usr/ports/work/mpv/pkg/usr/local/share/icons/hicolor/32x32/apps/mpv.png (from etc/mpv-icon-8bit-32x32.png)
+ install /usr/ports/work/mpv/pkg/usr/local/share/icons/hicolor/64x64/apps/mpv.png (from etc/mpv-icon-8bit-64x64.png)
+ install /usr/ports/work/mpv/pkg/usr/local/share/icons/hicolor/scalable/apps/mpv.svg (from etc/mpv-gradient.svg)
+ install /usr/ports/work/mpv/pkg/usr/local/share/icons/hicolor/16x16/apps/mpv.png (from etc/mpv-icon-8bit-16x16.png)
+ install /usr/ports/work/mpv/pkg/usr/local/share/icons/hicolor/symbolic/apps/mpv-symbolic.svg (from etc/mpv-symbolic.svg)
+ install /usr/ports/work/mpv/pkg/usr/local/bin/mpv (from build/mpv)
Waf: Leaving directory `/usr/ports/work/mpv/src/mpv/source/mpv/build'
'install' finished successfully (0.434s)
+ rm -r /usr/ports/work/mpv/pkg/usr/share/doc
rm: cannot remove '/usr/ports/work/mpv/pkg/usr/share/doc': No such file or directory
=======> ERROR: Building '/usr/ports/6c37-git/mpv/mpv#git-1.pkg.tar.gz' failed.

**Comment by onodera-punpun** [comment]
Thanks for reporting this :). Remove the `rm -r /usr/ports/work/mpv/pkg/usr/share/doc` line from the `Pkgfile` for now. I'll fix this tonight.

**Comment by mariojuniorjp** [comment]
Thanks! This works. :)

The only problem now is the mpv doesn't exist on system. Oo

$ mpv
bash: mpv: command not found
$ mpv -v
bash: mpv: command not found
$

**Comment by onodera-punpun** [comment]
do you actually install the package (`pkgmk -i`, `pkgmk -i -if -is` for ignoring the warnings because you changed the `Pkgfile`)?

**Comment by rtlanceroad** [comment]
@mariojuniorjp Hello. It looks like your mpv package is built and installed using `--prefix=/usr/local` instead of `--prefix=/usr`. If you did that, make sure your mpv binary is in your system path. You can check by `echo $PATH` in your terminal.
