### ISSUE TITLE
Use release/tar.gz version of the following packages: libuv, luajit, msgpack-c, msgpack-lua.

### ISSUE THREAD

**Issue by onodera-punpun** [6c37/crux-ports-git#4]
All of them have frequent releases and I think it's better to move them to crux-ports.

https://github.com/libuv/libuv/releases
http://luajit.org/
https://github.com/msgpack/msgpack-c/releases
https://github.com/fperrad/lua-MessagePack/releases

**Comment by kori** [comment]
Time to work.

**Comment by kori** [comment]
Done.
